### ISSUE TITLE
Error installing pipy package

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ai#30]
augerai works if cloned and installed locally but from pipy I get

pip install auger-ai
Collecting auger-ai
  Using cached https://files.pythonhosted.org/packages/fc/72/c670eb865a2615f6eeacfd75a7362983b7dd980e680e21066768f216ca5f/auger.ai-0.1.6-py3-none-any.whl
Requirement already satisfied: ruamel.yaml in ./my_env/lib/python3.7/site-packages (from auger-ai) (0.15.97)
Requirement already satisfied: requests in ./my_env/lib/python3.7/site-packages (from auger-ai) (2.22.0)
Requirement already satisfied: shortuuid in ./my_env/lib/python3.7/site-packages (from auger-ai) (0.5.0)
Requirement already satisfied: auger-hub-api-client>=0.5.6 in ./my_env/lib/python3.7/site-packages (from auger-ai) (0.6.1)
Requirement already satisfied: click in ./my_env/lib/python3.7/site-packages (from auger-ai) (7.0)
Requirement already satisfied: certifi>=2017.4.17 in ./my_env/lib/python3.7/site-packages (from requests->auger-ai) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./my_env/lib/python3.7/site-packages (from requests->auger-ai) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in ./my_env/lib/python3.7/site-packages (from requests->auger-ai) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./my_env/lib/python3.7/site-packages (from requests->auger-ai) (3.0.4)
Installing collected packages: auger-ai
Successfully installed auger-ai
(my_env)
 ✔ user  ~/deeplearn/auger-ai   master 
 $ augerai
Traceback (most recent call last):
  File "/Users/user/deeplearn/auger-ai/my_env/bin/augerai", line 6, in <module>
    from auger.cli.cli import cli
  File "/Users/user/deeplearn/auger-ai/my_env/lib/python3.7/site-packages/auger/cli/cli.py", line 5, in <module>
    from .utils.context import CONTEXT_SETTINGS, pass_context
ModuleNotFoundError: No module named 'auger.cli.utils'
(my_env)

**Comment by IgorFlint** [comment]
Fixed in 0.1.9, uploaded to pypi
