### ISSUE TITLE
Results from leaderboard show 'model id'

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ai#43]
Getting experiment leaderboard returns array of dictionaries that has 'model id'. Its documented as 'model_id' which makes more sense to me.  We should change.

[{'model id': '07AD07BC4893415', 'f1_macro': '0.2665', 'algorithm': 'BaselineClassifier'}, {'model id': '1351BA1F72024D3', 'f1_macro': '0.5852', 'algorithm': 'SVC'}, {'model id': '9676E1007DC641A', 'f1_macro': '0.6855', 'algorithm': 'SVC'}, {'model id': 'D09E5BE951764EE', 'f1_macro': '0.9330', 'algorithm': 'GradientBoostingClassifier'},

**Comment by IgorFlint** [comment]
`model id` comes from the server, so it may be more relevant to hub repo, not this one.
Though I will rename the field on client-side.

**Comment by derekflint** [comment]
I will file for hub then

**Comment by IgorFlint** [comment]
Then we better not to add dirty hacks to auger-ai and close this issue?

**Comment by derekflint** [comment]
I agree
