### ISSUE TITLE
Dataset create with local file as source always fails

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ai#47]
I have a local file iris.csv in same directory as script. I get:

`FileNotFoundError('auger-auger-mt-efl4si/workspace/projects/iris_project/files/mcgJAmW5GZMWKpMeM82qfZ-iris.csv')`

from auger.api.dataset import DataSet
from auger.api.utils.context import Context
from auger.api.project import Project

ctx = Context()
project = Project(ctx, project_name)
dataset_name = 'Iris'
    

dataset = DataSet(ctx, project, dataset_name).create('iris.csv')
ctx.log('Created dataset %s' % dataset.name)

**Comment by vlad-dplrn** [comment]
fixed, please verify
